### PR TITLE
refactoring histogram

### PR DESCRIPTION
**Pull request by HenryGeorgist**

### CODE REVIEW

**Comment by HenryGeorgist** [comment]
I am failing two tests. It comes down to intent. is the mean the mean of the histogram or the data itself? is the standard deviation the standard deviation of the data or the histogram itself?

**Review by rnugent3 — APPROVED** [review]
Looks great! Thanks, Will.

**Comment by rnugent3** [comment]
Seems like we should ask for the mean and the standard deviation of the histogram rather than the data?

**Comment by HenryGeorgist** [comment]
> Seems like we should ask for the mean and the standard deviation of the histogram rather than the data?

i have a property of Mean and a function of HistogramMean

**Comment by HenryGeorgist** [comment]
pushing this will break fda_model again, because we dont use data anymore. But i think it is an improvement

**Comment by rnugent3** [comment]
> > Seems like we should ask for the mean and the standard deviation of the histogram rather than the data?
> 
> i have a property of Mean and a function of HistogramMean

I see. And it looks like you update the sample mean each time you add an observation so you can throw out the sample but still have the sample mean?

Should we add documentation or refine naming to make it clear that Mean is the sample mean?

**Comment by HenryGeorgist** [comment]
I was thinking we could rename the properties as MeanOfData StandardDeviationOfData MinOfData, and MaxOfData or something like that.

Documentation would be great.

**Pull request merged**
